# Generated by Django 4.0.4 on 2022-05-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discounts',
        ),
    ]
